routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.'], function (){

    Route::get('/', 'AuthController@showLoginForm')->name('login');

    Route::post('login', 'AuthController@login')->name('login.do');

    /** Cadastro de usuário */
    Route::get('cadastrar', 'AuthController@register')->name('register');
    Route::post('cadastrar', 'AuthController@registerDo')->name('register.do');

    /** Validação de e-mail */
    Route::get('active-email/{token}', 'AuthController@activeEmail')->name('active.email');

    /** Reset Password */
    Route::get('reset', 'ResetPasswordController@resetPassword')->name('resetPassword');
    Route::post('reset', 'ResetPasswordController@resetPasswordDo')->name('resetPassword.do');
    Route::get('reset/{token}', 'ResetPasswordController@password')->name('password');
    Route::post('reset/token', 'ResetPasswordController@passwordDo')->name('password.do');

    Route::group(['middleware' => ['auth']], function (){

        Route::get('/home', 'AuthController@home')->name('home');

        Route::get('/documentos', 'DocumentsController@index')->name('documents.index');


        //Route::get('users/team', 'UserController@team')->name('users.team');
        //Route::resource('users', 'UserController');
    });


    Route::get('logout', 'AuthController@logout')->name('logout');
});

resources/views/admin/master/master.blade.php
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=0">

    <link rel="stylesheet" href="{{ url(mix('backend/assets/css/reset.css')) }}"/>
    <link rel="stylesheet" href="{{ url(mix('backend/assets/css/libs.css')) }}">
    <link rel="stylesheet" href="{{ url(mix('backend/assets/css/boot.css')) }}"/>
    <link rel="stylesheet" href="{{ url(mix('backend/assets/css/style.css')) }}"/>
    @hasSection('css')
        @yield('css')
    @endif

    <link rel="icon" type="image/png" href="{{ url(asset('backend/assets/images/favicon.png')) }}"/>

    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>UpAdmin - Site Control</title>
</head>
<body>

<div class="ajax_load">
    <div class="ajax_load_box">
        <div class="ajax_load_box_circle"></div>
        <p class="ajax_load_box_title">Aguarde, carregando...</p>
    </div>
</div>

<div class="ajax_response"></div>

<div class="dash">
    <aside class="dash_sidebar">
        <article class="dash_sidebar_user">
            <img class="dash_sidebar_user_thumb" src="{{ url(asset('backend/assets/images/avatar.jpg')) }}" alt="" title=""/>

            <h1 class="dash_sidebar_user_name">
                <a href="">Gustavo Web</a>
            </h1>
        </article>

        <ul class="dash_sidebar_nav">
            <li class="dash_sidebar_nav_item {{ isActive('admin.home') }}">
                <a class="icon-home" href="{{ route('admin.home') }}">Home</a>
            </li>

            <li class="dash_sidebar_nav_item {{ isActive('admin.documents.index') }}">
                <a class="icon-folder-open" href="{{ route('admin.documents.index') }}">Documentos</a>
            </li>
            <li class="dash_sidebar_nav_item ">
                <a class="icon-clock-o" href="">Em Processo</a>
            </li>
            <li class="dash_sidebar_nav_item">
                <a class="icon-check-circle" href="">Finalizados</a>
            </li>
            <li class="dash_sidebar_nav_item">
                <a class="icon-times-circle" href="">Cancelados</a>
            </li>
            <li class="dash_sidebar_nav_item">
                <a class="icon-trash" href="">Lixeira</a>
            </li>
<!--
            <li class="dash_sidebar_nav_item"><a class="icon-users" href="">Clientes</a>
                <ul class="dash_sidebar_nav_submenu">
                    <li class=""><a href="">Ver Todos</a></li>
                    <li class=""><a href="dashboard.blade.php?app=companies/index">Empresas</a></li>
                    <li class=""><a href="">Time</a></li>
                    <li class=""><a href="">Criar Novo</a></li>
                </ul>
            </li>
            <li class="dash_sidebar_nav_item"><a class="icon-home" href="dashboard.blade.php?app=properties/index">Imóveis</a>
                <ul class="dash_sidebar_nav_submenu">
                    <li class=""><a href="dashboard.blade.php?app=properties/index">Ver Todos</a></li>
                    <li class=""><a href="dashboard.blade.php?app=properties/create">Criar Novo</a></li>
                </ul>
            </li>
            <li class="dash_sidebar_nav_item"><a class="icon-file-text" href="dashboard.blade.php?app=contracts/index">Contratos</a>
                <ul class="dash_sidebar_nav_submenu">
                    <li class=""><a href="dashboard.blade.php?app=contracts/index">Ver Todos</a></li>
                    <li class=""><a href="dashboard.blade.php?app=contracts/create">Criar Novo</a></li>
                </ul>
            </li>
            <li class="dash_sidebar_nav_item"><a class="icon-reply" href="">Ver Site</a></li>
 -->
            <li class="dash_sidebar_nav_item"><a class="icon-sign-out on_mobile" href="{{ route('admin.logout') }}" target="_blank">Sair</a></li>

        </ul>

    </aside>

    <section class="dash_content">

        <div class="dash_userbar">
            <div class="dash_userbar_box">
                <div class="dash_userbar_box_content">
                    <span class="icon-align-justify icon-notext mobile_menu transition btn btn-green"></span>
                    <h1 class="transition">
                        <i class="icon-imob text-orange"></i><a href="">Up<b>Admin</b></a>
                    </h1>
                    <div class="dash_userbar_box_bar no_mobile">
                        <a class="text-red icon-sign-out" href="{{ route('admin.logout') }}">Sair</a>
                    </div>
                </div>
            </div>
        </div>

        <div class="dash_content_box">
            @yield('content')
        </div>
    </section>
</div>


<script src="{{ url(mix('backend/assets/js/jquery.js')) }}"></script>
<script src="{{ url(asset('backend/assets/js/tinymce/tinymce.min.js')) }}"></script>
<script src="{{ url(mix('backend/assets/js/libs.js')) }}"></script>
<script src="{{ url(mix('backend/assets/js/scripts.js')) }}"></script>

@hasSection('js')
    @yield('js')
@endif

</body>
</html>